setwd("/groups/stark/vloubiere/projects/pe_STARRSeq/")

# List scripts present in main file
files <- readLines("git_peSTARRSeq/main.R")
files <- grep("^  file.edit", files, value = T)
files <- data.table(file= unlist(tstrsplit(files, '"', keep=2)))
files[, check:= file.exists(file)]
# List scripts present in subscripts folder
check_old <- data.table(file= list.files("git_peSTARRSeq/subscripts", full.names = T))
check_old[, check:= file %in% files$file]
# Remove all files that are not present in main
check_old[!(check), 
          {
            # file.remove(file) ---->> VERY DANGEROUS!
          }]

# List all pdfs generated by scripts from main
PDF <- data.table(script= list.files("git_peSTARRSeq/subscripts/", full.names = T))
PDF <- PDF[, readLines(script), script]
PDF <- PDF[grepl("^pdf\\(", V1)]
PDF[, V1:= tstrsplit(V1, '"', keep= 2)]

# List pdf files existing in folder
check_old <- data.table(file= list.files("pdf", recursive = T, full.names = T))
check_old[, check:= file %in% PDF$V1]
# Move all pdf files that should not be there to pdf/old
check_old[!(check), old_dir:= paste0("pdf/old/", basename(file)), file]
check_old[!(check) & old_dir!=file, file.rename(file, old_dir, overwrite= T), file]
